// source/options/feature-list.svelte
<svelte:options
	customElement={{
		tag: 'feature-list',
		shadow: 'none',
	}}
/>

<script lang="ts">
	import domify from 'doma';
	import {closestElement} from 'select-dom';

	import {featuresMeta, importedFeatures} from '../feature-data.js';
	import {getLocalHotfixes} from '../helpers/hotfix.js';
	import {createRghIssueLink, getFeatureUrl} from '../helpers/rgh-links.js';

	const host = $host();
	const features = featuresMeta.filter(feature =>
		importedFeatures.includes(feature.id)
	);

	let hotfixes = $state(new Map<string, number>());
	let filter = $state('');
	let offCount = $state(0);

	function keywordsOf(value: string): string[] {
		return value.toLowerCase().replaceAll(/\W/g, ' ').split(/\s+/).filter(
			Boolean,
		);
	}

	function isHidden(text: string): boolean {
		return keywordsOf(filter).some(word => !text.includes(word));
	}

	function updateOffCount(): void {
		offCount = host.querySelectorAll('.feature-checkbox:not(:checked)').length;
	}

	function sort(): void {
		const container = host.querySelector('.js-features')!;
		const items = [...container.querySelectorAll<HTMLElement>('.feature')]
			.toSorted((a, b) => a.dataset.text!.localeCompare(b.dataset.text!));
		const grouped = Object.groupBy(items, item => {
			const checkbox = item.querySelector<HTMLInputElement>(
				'input.feature-checkbox',
			)!;
			return checkbox.checked ? 'on' : checkbox.disabled ? 'broken' : 'off';
		});

		for (const group of [grouped.off, grouped.broken, grouped.on]) {
			if (group) {
				for (const item of group) {
					container.append(item);
				}
			}
		}
	}

	function toggleScreenshot(event: MouseEvent): void {
		if (event.ctrlKey || event.metaKey || event.shiftKey) {
			return;
		}

		event.preventDefault();
		if (event.altKey) {
			for (
				const toggle of host.querySelectorAll<HTMLInputElement>(
					'input.screenshot-toggle',
				)
			) {
				toggle.checked = !toggle.checked;
			}
		} else {
			const toggle = closestElement(
				'.feature',
				event.currentTarget as HTMLElement,
			)!
				.querySelector<HTMLInputElement>('input.screenshot-toggle')!;
			toggle.checked = !toggle.checked;
		}
	}

	function mount(element: HTMLElement, node: Node): {destroy(): void} {
		element.append(node);
		return {
			destroy() {
				node.parentNode?.removeChild(node);
			},
		};
	}

	host.addEventListener('sync', () => {
		sort();
		updateOffCount();
	});

	void getLocalHotfixes().then(entries => {
		hotfixes = new Map(
			entries.filter(([feature]) => importedFeatures.includes(feature)),
		);
		updateOffCount();
		host.dispatchEvent(new Event('ready'));
	});
</script>

<details id="features">
	<summary>
		<strong class="features-header">
			🔋 Features: {features.length + 25}
			{#if offCount > 0}
				({
					offCount === features.length
					? 'JS off… are you breaking up with me?'
					: `${offCount} off`
				})
			{/if}
		</strong>
	</summary>
	<div>
		<p>
			<input
				type="text"
				placeholder="Find features"
				spellcheck="false"
				autocomplete="off"
				autocapitalize="off"
				bind:value={filter}
			>
			<small>Use the "Identify feature" section below if you can't find what
				you're looking for.</small>
		</p>
		<div class="js-features">
			{#each features as feature (feature.id)}
				{@const issue = hotfixes.get(feature.id)}
				{@const text = `${feature.id} ${feature.description}`.toLowerCase()}
				<div class="feature" data-text={text} hidden={isHidden(text)}>
					<input
						type="checkbox"
						name={issue ? undefined : `feature:${feature.id}`}
						id={feature.id}
						class="feature-checkbox"
						disabled={Boolean(issue)}
						onchange={updateOffCount}
					>
					<div class="info">
						<label class="feature-name" for={feature.id}>{feature.id}</label>
						<a href={getFeatureUrl(feature.id)} class="feature-link">source</a>
						<input hidden type="checkbox" class="screenshot-toggle">
						{#if feature.screenshot}
							<a
								href={feature.screenshot}
								class="screenshot-link"
								onclick={toggleScreenshot}
							>screenshot</a>
						{/if}
						{#if issue}
							<span class="hotfix-notice">
								(Disabled due to <span
									use:mount={createRghIssueLink(issue, true)}
								></span>)</span>
						{/if}
						<p class="description" use:mount={domify(feature.description)}></p>
						{#if feature.screenshot}
							<img
								hidden
								src={feature.screenshot}
								loading="lazy"
								class="screenshot"
							>
						{/if}
					</div>
				</div>
			{/each}
		</div>
	</div>
</details>

// source/options/feature-list.tsx
import React from 'dom-chef';
import domify from 'doma';
import delegate, {type DelegateEvent} from 'delegate-it';
import {countElements} from 'select-dom';
import {$, $$} from 'select-dom/strict.js';

import {getLocalHotfixes} from '../helpers/hotfix.js';
import {createRghIssueLink, getFeatureUrl} from '../helpers/rgh-links.js';
import {importedFeatures, featuresMeta} from '../feature-data.js';

function moveDisabledFeaturesToTop(): void {
	const container = $('.js-features');
	const features = $$('.feature').toSorted((a, b) => a.dataset.text!.localeCompare(b.dataset.text!));
	const grouped = Object.groupBy(features, feature => {
		const checkbox = $('input.feature-checkbox', feature);
		return checkbox.checked ? 'on' : checkbox.disabled ? 'broken' : 'off';
	});
	for (const group of [grouped.off, grouped.broken, grouped.on].filter(Boolean)) {
		for (const feature of group!) {
			container.append(feature);
		}
	}
}

async function markLocalHotfixes(): Promise<void> {
	for (const [feature, relatedIssue] of await getLocalHotfixes()) {
		if (importedFeatures.includes(feature)) {
			const input = $<HTMLInputElement>('#' + feature);
			input.disabled = true;
			input.removeAttribute('name');
			$(`.feature-name[for="${feature}"]`).after(
				<span className="hotfix-notice"> (Disabled due to {createRghIssueLink(relatedIssue)})</span>,
			);
		}
	}
}

function buildFeatureCheckbox({id, description, screenshot}: FeatureMeta): HTMLElement {
	return (
		<div className="feature" data-text={`${id} ${description}`.toLowerCase()}>
			<input type="checkbox" name={`feature:${id}`} id={id} className="feature-checkbox" />
			<div className="info">
				<label className="feature-name" htmlFor={id}>{id}</label>
				{' '}
				<a href={getFeatureUrl(id)} className="feature-link">
					source
				</a>
				<input hidden type="checkbox" className="screenshot-toggle" />
				{screenshot && (
					<a href={screenshot} className="screenshot-link">
						screenshot
					</a>
				)}
				<p className="description">{domify(description)}</p>
				{screenshot && (
					<img hidden src={screenshot} loading="lazy" className="screenshot" />
				)}
			</div>
		</div>
	);
}

function summaryHandler(event: DelegateEvent<MouseEvent>): void {
	if (event.ctrlKey || event.metaKey || event.shiftKey) {
		return;
	}

	event.preventDefault();
	if (event.altKey) {
		for (const toggle of $$('input.screenshot-toggle')) {
			toggle.checked = !toggle.checked;
		}
	} else {
		const toggle = event
			.delegateTarget
			.closest('.feature')!
			.querySelector('input.screenshot-toggle')!;
		toggle.checked = !toggle.checked;
	}
}

function featuresFilterHandler(this: HTMLInputElement): void {
	const keywords = this
		.value
		.toLowerCase()
		.replaceAll(/\W/g, ' ')
		.split(/\s+/)
		.filter(Boolean); // Ignore empty strings
	for (const feature of $$('.feature')) {
		feature.hidden = !keywords.every(word => feature.dataset.text!.includes(word));
	}
}

const offCount = new Text();

function updateOffCount(): void {
	const count = countElements('.feature-checkbox:not(:checked)');
	switch (count) {
		case 0: {
			offCount.nodeValue = '';
			break;
		}

		case countElements('.feature-checkbox'): {
			offCount.nodeValue = '(JS off… are you breaking up with me?)';
			break;
		}

		default: {
			offCount.nodeValue = `(${count} off)`;
		}
	}
}

export default async function initFeatureList(): Promise<void> {
	// Generate list
	$('.js-features').append(...featuresMeta
		.filter(feature => importedFeatures.includes(feature.id))
		.map(feature => buildFeatureCheckbox(feature)),
	);

	// Add notice for features disabled via hotfix
	await markLocalHotfixes();

	// Load screenshots
	delegate('.screenshot-link', 'click', summaryHandler);

	// Filter feature list
	$('input#filter-features').addEventListener('input', featuresFilterHandler);

	// Add feature count. CSS-only features are added approximately
	$('.features-header').append(`: ${featuresMeta.length + 25} `, offCount);

	delegate('.feature-checkbox', 'change', updateOffCount);
}

export function updateListDom(): void {
	moveDisabledFeaturesToTop();
	updateOffCount();
}
