// source/features/repo-header-info.svelte
<script lang="ts">
	import RepoForkedIcon from 'octicons-plain-react/RepoForked';
	import StarIcon from 'octicons-plain-react/Star';
	import StarFillIcon from 'octicons-plain-react/StarFill';

	import {buildRepoUrl} from '../github-helpers/index.js';
	import abbreviateNumber from '../helpers/abbreviate-number.js';
	import DomChef from '../helpers/dom-chef.svelte';
	import type {RepositoryInfo} from './repo-header-info.js';

	const {info}: {info: RepositoryInfo} = $props();
</script>

{#if info.ciCommit}
	<span
		class="rgh-ci-link d-none d-sm-flex flex-items-center flex-justify-center p-1 tmp-p-1 Button Button--invisible"
		title="CI status of latest commit"
	>
		<batch-deferred-content
			hidden
			data-url={buildRepoUrl('commits/checks-statuses-rollups')}
		>
			<input
				name="oid"
				value={info.ciCommit}
				data-targets="batch-deferred-content.inputs"
			/>
		</batch-deferred-content>
	</span>
{/if}

{#if info.stargazerCount > 1}
	<a
		href={buildRepoUrl('stargazers')}
		title={`Repository starred by ${info.stargazerCount.toLocaleString('us')} people${
			info.viewerHasStarred ? ', including you' : ''
		}`}
		class="d-none d-sm-flex flex-items-center flex-justify-center gap-1 p-1 tmp-p-1 color-fg-muted Button Button--invisible"
	>
		<DomChef
			as={info.viewerHasStarred ? StarFillIcon : StarIcon}
			width={12}
			height={12}
			color={info.viewerHasStarred ? 'var(--button-star-iconColor)' : undefined}
		/>
		<span class="f5">{abbreviateNumber(info.stargazerCount)}</span>
	</a>
{/if}

{#if info.forked}
	<a
		href={info.forked.url}
		class="d-none d-sm-flex flex-items-center flex-justify-center p-1 tmp-p-1 Button Button--invisible"
	>
		<DomChef as={RepoForkedIcon} class="m-0 tmp-m-0" width={12} height={12} />
	</a>
{/if}

// source/features/repo-header-info.tsx
import * as pageDetect from 'github-url-detection';
import LockIcon from 'octicons-plain-react/Lock';
import RepoForkedIcon from 'octicons-plain-react/RepoForked';
import StarIcon from 'octicons-plain-react/Star';
import StarFillIcon from 'octicons-plain-react/StarFill';
import React from 'dom-chef';
import {elementExists} from 'select-dom';
import {CachedFunction} from 'webext-storage-cache';

import observe from '../helpers/selector-observer.js';
import features from '../feature-manager.js';
import api from '../github-helpers/api.js';
import GetRepositoryInfo from './repo-header-info.gql';
import {buildRepoURL, cacheByRepo} from '../github-helpers/index.js';
import abbreviateNumber from '../helpers/abbreviate-number.js';

type RepositoryInfo = {
	isFork: boolean;
	isPrivate: boolean;
	stargazerCount: number;
	viewerHasStarred: boolean;
};

const repositoryInfo = new CachedFunction('stargazer-count', {
	async updater(): Promise<RepositoryInfo> {
		const {repository} = await api.v4(GetRepositoryInfo);
		return repository;
	},
	maxAge: {days: 1},
	staleWhileRevalidate: {days: 3},
	cacheKey: cacheByRepo,
});

async function add(repoLink: HTMLAnchorElement): Promise<void> {
	const {isFork, isPrivate, stargazerCount, viewerHasStarred} = await repositoryInfo.get();

	// GitHub may already show this icon natively, so we match its position
	if (isPrivate && !elementExists('.octicon-lock', repoLink)) {
		repoLink.append(
			<LockIcon className="ml-1" width={12} height={12}/>,
		);
	}

	// GitHub may already show this icon natively, so we match its position
	if (isFork && !elementExists('.octicon-repo-forked', repoLink)) {
		repoLink.append(
			<RepoForkedIcon className="ml-1" width={12} height={12}/>,
		);
	}

	if (stargazerCount > 1) {
		repoLink.after(
			<a
				href={buildRepoURL('stargazers')}
				title={`Repository starred by ${stargazerCount.toLocaleString('us')} people`}
				className="d-flex flex-items-center flex-justify-center mr-1 gap-1 color-fg-muted"
			>
				{
					viewerHasStarred
						? <StarFillIcon className="ml-1" color="var(--button-star-iconColor)" width={12} height={12}/>
						: <StarIcon className="ml-1" width={12} height={12}/>
				}
				<span className="f5">{abbreviateNumber(stargazerCount)}</span>
			</a>,
		);
	}
}

function init(signal: AbortSignal): void {
	observe('.AppHeader-context-full li:last-child a.AppHeader-context-item', add, {signal});
}

void features.add(import.meta.url, {
	include: [
		pageDetect.hasRepoHeader,
	],
	init,
});

/*
Test URLs

- Regular: https://github.com/refined-github/refined-github
- Fork: https://github.com/134130/refined-github
- Fork with native icon: https://github.com/refined-github/fork
- Private: https://github.com/refined-github/private
- Private fork: https://github.com/refined-github/fork

*/
